### ISSUE TITLE
diy一次隐秘的封号抗议💢

### ISSUE THREAD

**Issue by AMOS091** [diylove/wiki#121]
`diy一次封号抗议`的隐秘版指南📖

小黄向朋友要来他抱怨b站封号的朋友圈的截图，打印成了小广告一样的贴纸，到Bilibili上海总部建筑群周围贴了一圈。

## 前言

大约在2020年四月份，一位朋友策划了一场叫“绘画是观念艺术家的通行证，观念是绘画艺术家的墓志铭”的虚拟展览。当时他用B站进行了直播导览。直播结束后，他的B站账号即遭到了永久封停。事发不久后B站发布一部叫《后浪》宣传片，大肆宣传其是后起之秀、精神物质丰满年轻人的平台。面对平台一边打压创作者，一边忽略现实美化社会的宣传，被封号的那位朋友愤愤不平的发了一条朋友圈：

<img width="337" alt="截屏2021-11-13 12 05 44" src="https://user-images.githubusercontent.com/91636953/141660727-f36d82ed-f003-4e54-8202-16161d95bc0e.png">

我也对封号者和B站的所作所为生气。见证了疫情初期封号狂潮，面对平台权力的滥用我们只能憋闷气，在朋友圈里抱怨，十分无力。一直在想怎么让它们更可见有力一点，正好后来有机会去上海，就做了这次借言上访小行动。

<img width="553" alt="截屏2021-11-12 19 26 50" src="https://user-images.githubusercontent.com/91636953/141660826-ecf409eb-bb32-4e27-890e-166287579263.png"> 

*B站icon雕像

<img width="1215" alt="截屏2021-11-13 14 39 32" src="https://user-images.githubusercontent.com/91636953/141660856-070af263-d29c-4921-8294-c4cb8018ec57.png">

*不少路过这个地标的人都会拍或合影，刚贴完就有人拍了它

![bi站大樓](https://user-images.githubusercontent.com/91636953/141660886-fcc720ad-d193-4d6e-8739-7827cc4665e2.jpg)
*手机内置地图帮我记录了贴的位置

贴了13个在附近的共享单车上;约40个在建筑设施、植物、地标上。
从打印裁剪到完成，一个下午就搞定。
<img width="751" alt="截屏2021-11-12 19 27 12" src="https://user-images.githubusercontent.com/91636953/141663994-a92bc2df-c679-48c5-bfd1-dd5a0b364963.png">

![WechatIMG909](https://user-images.githubusercontent.com/91636953/141661510-ef189fd8-3957-4e50-bfc8-59878f13bad3.jpeg)
*Bilibili总部大楼侧面，很多b站人员经过。贴纸在一个玻璃之间的结构上，旁边就是711。

> > 哇所以后续有反馈嘛？（来自b站的、路人的..
> 
> 哈哈，其实我贴的很慢，在外面呆久了感觉特别冷，然后晚上要赶着见一个朋友吃饭，所以做完就迅速逃跑了。 另外真的到处都是挂牌的b站打工人，找时机贴完也有点不好意思逗留，几乎没怎么记录🥲，下次试试。 不过，我贴的有些地方挺明显的，比如入口电线杆之类，一定会有人看到。 “从朋友圈出圈” 的目的肯定达到了。 具体反应我也不是很清楚，毕竟大家没在街上看过这种东西。

## 💰成本
到达地点的交通费+不干胶贴纸打印费。贴纸一张彩色A4大小一般不会超过5元。 我打印了两张A2没超过20元

### 🔧材料：
1. 对国内大互联网公司的不满
2. 不干胶贴纸，很多打印店都可以打印，网上也可以打。（另空白的A4不干胶纸在不少文具店或网上都有卖， 家里有打印机的可以在家打印，一般放到普通A4纸的纸槽里就行。 ）
3. 去其公司总部附近的机会

> 北京 上海 四川省（成都） 广东省（深圳） 浙江省（杭州）都至少有一个互联网巨头， 如果你不喜欢它们，都可以一试。

<img width="382" alt="截屏2021-11-13 14 59 15" src="https://user-images.githubusercontent.com/91636953/141663779-fd885f10-7f54-4acb-8a80-fffa457788b6.png">
<img width="570" alt="截屏2021-11-13 14 26 11" src="https://user-images.githubusercontent.com/91636953/141663780-96443e02-56dc-45d7-949e-eac9a2dc8056.png">

### 🕵️准备过程：

1. 写下你对封号审查平台的不满。新浪，微信，b站，豆瓣等等等..
2. 将他们排版成小广告的尺寸，不会ps可以找打印店或amos帮忙
3. 打印成不干胶纸贴纸，裁剪
4. 推荐准备比较方便装小贴纸的裤子/衣服，工装裤就挺合适。
5. 找到你想抗议的公司总部方位，在实施前去那里先实地勘察一下

**💡注：**

1. 选择不干胶贴纸一方面较为便利好找，另一方面是它们不算是过于难清理的贴纸，不会为清洁者造成过多麻烦。若觉得有更好的选择请自行发挥： ）
2. 勘查时注意：哪里保安多，哪里人流量多，在哪里贴不容易立马就被发现等等。如b站公司总部下面是商业中心，有食堂，下班时间到处都是挂着牌子的在b站上班的工作人员。因此想保持过程的隐秘性推荐避开早晚高峰。
3. 也不要过于敏感哦！ 小心进局子。 抱怨抱怨，规模比较小比较可行。虽然好像比起大字报要弱很多 ，但是能够安全👷‍♀️并且留存的久，才是最有效率的方法。
4. 胆小的朋友（我也胆小）贴一贴附近的共享单车其实也是一个好方法， 因为很多下班族都会骑，而且很多车上已经好多小广告了。

### 🚶现场：

> 能想到的合适的比喻就是模拟恐怖分子按炸弹的心理

1. 放轻松，就像其他来参观大公司的游客，或者散步的人一样。发声有理，不该心虚：）。 也可以一边慢跑一边贴。
2. 想贴的地方有时人很多，所以做好在这个区域多转悠一段时间的准备。也可以坐下来休息等一会儿，读会儿书。
3. 根据勘查状况和现场见仁见智:

> 因为不打算正面交锋，后来到了下班时间很多人，很多时候需要灵活应用，在这里动用了挺多创意和表演脑筋的：比如总部大楼门口前垃圾桶， 总是有几个人在那里吸烟，直接走过去太明显了。当时我利用了手里的咖啡，把贴纸准备好压在杯子下，在垃圾桶旁喝了几口后，然后直接把杯子放在了垃圾桶上，完成了操作。

<img width="578" alt="截屏2021-11-14 01 08 41" src="https://user-images.githubusercontent.com/91636953/141663729-340bd57e-5b51-4607-b0ea-99a9e4ee85ff.png"> 
没人了后又回来拍了一张，咖啡杯没了贴纸还在。

4.🤳贴完后如果方便可以拍一张，现在大多智能手机都有照片定位功能，拍完就可以拥有贴过地方的小地图。

## 👀延伸阅读：

Suazme Lacy 的实践与她的“新公共艺术”概念：
<img width="1197" alt="截屏2021-11-14 00 24 20" src="https://user-images.githubusercontent.com/91636953/141663966-1cd5a33e-ebf8-4f63-b045-9d1ffde37794.png">

在Lacy1977年的实践《5月的三个星期》中，她到被记录在案的强奸犯罪发生的具体地点，在街头用红字记录了下来。这件事当时产生了巨大的影响，引起了真正的社会变化。
网站：
https://www.suzannelacy.com/performance-installation#/three-weeks-in-may/
“这种新型公共艺术历史的构建不是建立在材料，空间或艺术媒体的类型学基础上，而是建立在受众，关系，交流和政治意图的概念上。我的前提是，当前公共艺术的真正遗产来自很大程度上被边缘化的艺术家的话语”（1995.p28）”-Lacy, Suzanne. Mapping the Terrain: New Public Genre Art. US: Bay Press, 1995.

<img width="909" alt="截屏2021-11-13 19 00 07" src="https://user-images.githubusercontent.com/91636953/141661691-80cb2b35-4737-4e0e-be86-fa16f9c8a4d1.png">
**B站真实版《后浪》**
一位B站up主做的真实重制版，很有意思，已删，youtube观看链接：
https://www.youtube.com/watch?v=CHaQ2_CpWqc
<img width="1110" alt="截屏2021-11-13 11 55 19" src="https://user-images.githubusercontent.com/91636953/141661654-e68c49e8-1abe-463c-a7e7-ccdbcf7ae2e2.png">
**绘画是观念艺术家的通行证，观念是绘画艺术家的墓志铭**
需要百度网盘版本为可找小兔子飞走了要 
https://www.youtube.com/watch?v=HSMIKeLe984

**Comment by JianqiaoJ** [comment]
哇所以后续有反馈嘛？（来自b站的、路人的..

**Comment by AMOS091** [comment]
> 哇所以后续有反馈嘛？（来自b站的、路人的..

哈哈，其实我贴的很慢，在外面呆久了感觉特别冷，然后晚上要赶着见一个朋友吃饭，所以做完就迅速逃跑了。 另外真的到处都是挂牌的b站打工人，找时机贴完也有点不好意思逗留，几乎没怎么记录🥲，下次试试。 不过，我贴的有些地方挺明显的，比如入口电线杆之类，一定会有人看到。 “从朋友圈出去” 的目的肯定达到了。  具体反应我也不是很清楚，毕竟大家没在街上看过这种东西。

**Comment by JianqiaoJ** [comment]
> > 哇所以后续有反馈嘛？（来自b站的、路人的..
> 
> 哈哈，其实我贴的很慢，在外面呆久了感觉特别冷，然后晚上要赶着见一个朋友吃饭，所以做完就迅速逃跑了。 另外真的到处都是挂牌的b站打工人，找时机贴完也有点不好意思逗留，几乎没怎么记录🥲，下次试试。 不过，我贴的有些地方挺明显的，比如入口电线杆之类，一定会有人看到。 “从朋友圈出圈” 的目的肯定达到了。 具体反应我也不是很清楚，毕竟大家没在街上看过这种东西。

我觉得b站公关部的员工理应要有这个敏感度关注到hhhh
