### ISSUE TITLE
diy阳光男孩穿搭

### ISSUE THREAD

**Issue by yongooo** [diylove/wiki#129]
背景
我妈和我姐每次见我都说我穿的很老土，这样下去会一直找不到女朋友。反视我自己，我的穿着打扮确实不咋地，灰不溜秋，不太讲究。因为从事的是儿童艺术教育，我也想把自己打扮的阳光有活力一点，所以，我觉的可以做些改变，但是我该怎么做呢？（还没想清楚，走过路过看到此条目的你，请提出宝贵建议哈哈）

材料
1. 现有的衣服
2. 剪刀✂️
3. 彩色笔、铅笔、水性笔
4. 纸
5. 针、线
6. 大镜子（去借）
（预算:50元以内）

过程步骤
1. 把自己所有的衣服找出来，进行分类。
2. 随意搭配看看。
3. 把自己全身简笔图画出来，在上面搭配各种颜色衣服看看。 （以上写于11月19日，以下11月21）
5. 搭配好了广东冬天的衣服!只有两三套，一点都不阳光，将就吧。想阳光可能要一些鲜亮的衣服，我现有的衣服都是灰暗的，除了一条天蓝色牛仔裤。

一个学了十几年美术的人，整天想着画面协不协调、整不整体的问题，却从未关注过自己的衣着的色彩搭配、布料搭配、长短大小合身和搭配，真是有些讽刺的事。![alt text](https://user-images.githubusercontent.com/92130571/142755196-2a3d4a89-d03c-489f-aa04-6f920d2aead0.jpg) （以下写于11月25日）

穿了4天自己重新搭配的旧衣服了，4天都不一样，心情特别好，人很自信（因为终于对自己的穿着心中有数了，而不是像以前那样各种臆想、怀疑）、心情很阳光，原来这是可以改变的。如果十几年前知道这样做就好了，因为穿着问题自卑矛盾和十几年，不过现在还不晚，真好。那种快乐和自信，很多来自于对自己的重新审视重新认识，把自己当成一个作品来装饰的那种有趣感和成就感。

**Comment by JianqiaoJ** [comment]
想到周杰伦的《阳光宅男》（bushi

**Comment by 2jojo** [comment]
私信找我吧！我这儿有好多衣服

**Comment by AMOS091** [comment]
<img width="762" alt="截屏2021-12-17 13 29 56" src="https://user-images.githubusercontent.com/91636953/146551872-247853ed-483c-41cf-af16-615d238a4da2.png">
饱和度100才阳光
