### ISSUE TITLE
diy一个六十分钟的微笑（弄假直到成真）

### ISSUE THREAD

**Issue by 2jojo** [diylove/wiki#24]
### 材料
家庭办公的衣服。计时器

### 要准备什么

没有。放松吧。

### 你要做什么：

摆一个姿势。开始计时。微笑，持续60分钟。

### 额外：

想象一下，你在跟一群人做这件事，感受一下气氛。（或者跟一群人视频连线，做这件事）

### 艺术家：

安娜·维特（Anna Witt）

www.performance-homework.work

**Comment by AMOS091** [comment]
不太严格地尝试了7，8分钟，弄假成真很快就做到了。可能是我笑肌不发达， 六十分钟感觉太难了， 要用手工耿的微笑辅助器才能完成 [https://www.bilibili.com/video/BV1tt41137uE/]
