### ISSUE TITLE
diy一场PPT之王争霸赛

### ISSUE THREAD

**Issue by haodonghhkj** [diylove/wiki#52]
### 背景
让每个人成为出色的PPTer，和出色的聆听者

### 材料
1. 电脑，幕布，投影仪，多余参与者的椅子

### 过程步骤
1. 活动报名，报名时每人准备5张图片5句话
2. 活动现场，每人现场准备3张图，3句话
3. 每人现场想两个任意问题，随意问题即可
4. 将所有图片和文字交叉混合，做多组8图8文字的ppt
5. 每人都要演讲，随机演讲者上场顺序，每人随机获得2个问题，演讲主题需要从问题中选一个
6. 演讲者演讲的时候，需要按照图片和文字来解决“问题”，演讲者有8分钟演讲时间，中途不能笑场
7. 听众需要一直保持面无表情的状态，不能笑场。
8. 演讲者结束以后，有10分钟的复盘时间，可以提出建议
9. 所有人结束后，大家匿名投票投出胜利者，成为本场PPT之王

**Comment by Jesse-zj** [comment]
脑洞很大，有趣哈哈
