### ISSUE TITLE
diy一次凌晨散步（或，在动弹不得时diy一种动弹）

### ISSUE THREAD

**Issue by usx1999** [diylove/wiki#56]
### 背景
在白天的工作让你很烦心、受不了的时候

### 材料
1. 腿、拐棍、轮椅……任何能移动自己的东西
2. 一个晚上
3. 一个室外空间
4. （可选）能拿着走的任何东西

### 过程步骤
1. 摆脱继续在桌前没完没了地坐下去、无效地空耗下去的惯性。感受你僵硬的腰腿多么需要活动，遵循它的意愿，站起来。
2. 你的头脑一片空白，你已经站起来但不知道接下来要做什么。你闭锁的房间里充满了无数个烦躁的日夜积累下来的习惯：手机、沙发、床……都呼唤你用旧的方式接触它们，但这次你没有兴趣回应它们的呼唤。在这个一切可能性都已经坍缩的房间中，你是一颗游离的原子，感受无处释放的势引起的烦躁不安。
3. 勇敢地迈出这个狭小的箱子吧，把自己像一件垃圾一样丢入未知的黑夜。此时的你是一个不可分类的东西，让熟悉的道路也变得动荡起来。但别忘了带钥匙。
4. 你可以带钱、带手机、带一个本子、带相机、带一本书、带烟、带任何东西。它们最好少而且小，可以揣在口袋里。背包会妨碍你感受或者想象一种漂浮。
5. 让身体和直觉替你选一条路，一条熟悉的走惯的路，也许会在中途转向意料之外的方向。去小卖部、去公交站、去河边、去一片待建的废墟……随便哪里，不要在一个路口太久地犹豫。
6. 看见野猫，看见张牙舞爪的树，听见水管给偷偷给草坪浇水的声音、闻到打烊的饭馆门口堆的厨余垃圾、也许远处一条熟悉的街道因为空旷和路灯不亮而显得陌生，看到橱窗上的倒影——想象黑夜如何把玻璃变成镜子，每天从某一刻开始，你的视线就不再能望穿这些透明的墙……看到自己的想法和黑暗交媾，逐渐生出变化，或者难产，而变化总在你放弃了凭意志去扭转什么的时候产生。

### 路径选择指南
1. 以数学的方式寻找新的路径。
你家附近的交叉路口，共有五个方向，从任意一个方向走向另一个方向，共有五乘四等于二十种可能性。你可以尝试每一种组合。假设这五个方向分别通往家门、商店、公园、别的小区，以及很远很远的地方，每一种组合就对应着一种特殊的经历和需要。这个路口汇聚了至少二十种经历。以这个路口为起点，你可以开始回忆，如果每个组合想起一件事，你可以想起二十件事。每多一个路口，组合数量就会再扩大一次。（见https://www.douban.com/note/729515135/）
2. 以多人游戏的方式寻找新的路径。
和其他人一起散步，叫醒刚刚睡下的朋友，拦住偶遇的陌生人……每次遇到岔路时，你们用石头剪刀布或者手心手背决定方向，e.g.“你赢了就往左我赢了就往右”。

### 散步的结束
1. 在你觉得够了的时候结束散步。也许你捉到了一两只无形的黑夜生物，把它们带回家，存放在纸上、墙上、柜子里……它们也许能让坍缩的房间重新激活。
2. 你会在另一个时候，被一个熟悉而陌生的理由催促着重新开始一次凌晨散步。记住，永远不要下一次散步抱有期待。你不是去开阔的地方体验生活，而被赶到街上。你总会被一个逼仄的地方排斥出去，这一次、永远是这样。

**Comment by 2jojo** [comment]
“想象黑夜如何把玻璃变成镜子，每天从某一刻开始，你的视线就不再能望穿这些透明的墙” 🌵
