### ISSUE TITLE
diy一场觉察实验

### ISSUE THREAD

**Issue by Bettermanhl** [diylove/wiki#60]
## 背景
感觉世界运转的节奏越来越快了，人的内心也跟着愈加浮躁，好像现在做任何事都要1.5倍速，2倍速的去做。我认为速度越快，越难以觉察，外界的变化和内心的细节都被忽略掉了。让我们尝试一次让自己的身体和内心都慢下来的察觉之旅。

## 材料
不需要任何材料

### 独自体验：
1. 准备一段独处的10分钟的时间
2. 设定10分钟倒计时
3. 计时开始后，放慢你所有的动作，0.5倍速，0.25倍速，最大限度的放慢。
4. 观察你的动作，感受情绪。

### 群体体验：
1. 邀请参与者7人以内
2. 找一个相对私密的空间
3. 给每个人分配一连串的小任务，可以是取一个物品，说一段话，背一首诗，两个人聊天等。
4. 倒计时一小时，所以参与者放慢动作，进行任务。
5. 准备相机或手机拍摄1小时内发生的过程。
6. 时间到了，大家可以交流分享这一小时的体验。

**Comment by yongooo** [comment]
我现在也发现自我觉察真的很重要。前两天参加了一场“新手心理咨询师入门演练”，深深的感受到我平时对自己的感受到忽视，或者不曾探究，不曾和它好好链接、深层链接，导致内耗严重
