### ISSUE TITLE
团队会议

### ISSUE THREAD

**Issue by yongooo** [diylove/wiki#85]
### 背景
没人喜欢开会，除了那个滔滔不绝的会议领导。“一言堂”的会议我们不喜欢，“一票否决”制的会议经常做不成事。怎么让会议成为推动行动的一个美丽发动机？

### 材料
1. 一张很大的白纸（四开或者对开）和笔。或者一个白板和笔。
2. 一个确实有必要开的会议。

### 过程步骤
1. 小组首先选出一名会议引导者，议程基于团队成员希望讨论的议题现场决定。引导者不允许发表任何观点、建议或决定，她/他只能提问:“你的提案是什么？”或“你提案的理由是什么？”等，所有的建议都写在一张白板纸上。
2. 第二轮用来讨论、改善和提炼各种提案。
3. 在第三轮中，团队将就该提案做出决定。
4. 做决定的基础不是达成共识，只要没有人有原则性的反对意见，一项解决方案就可以通过。如果出现新的信息，随时可以重新讨论之前通过的方案。
5. 过程中如果出现卡壳，可请外部引导者帮助，请那些有经验的处理过类似问题的人士或团队。

### 参考来源
《重塑组织》

### 延伸阅读
#34

**Comment by 2jojo** [comment]
优化了一下排版

**Comment by 2jojo** [comment]
“美丽发动机” 😄
